export {
  createAcceptSmartInkCompositeCommand,
  createAcceptSmartInkProposalCommand,
  smartInkProposalStillApplies,
} from "./commands";
export {
  proposeSmartInkComposite,
  smartInkCompositeRecognizerVersion,
  type SmartInkCompositeKind,
  type SmartInkCompositeProposal,
} from "./composite-recognizer";
export {
  smartInkDiagnosticSchemaVersion,
  subscribeSmartInkDiagnostics,
  type SmartInkDiagnosticReason,
  type SmartInkDiagnosticRecord,
} from "./diagnostics";
export {
  recognizeSmartInkArrow,
  smartInkArrowRecognizerVersion,
  type SmartInkArrowCandidate,
  type SmartInkArrowGeometry,
  type SmartInkArrowProposal,
} from "./arrow-recognizer";
export {
  createSmartInkReplacementObject,
  proposeSmartInkReplacement,
  smartInkCanvasRecognitionPolicy,
  type SmartInkBoardProposal,
  type SmartInkBoardCandidate,
  type SmartInkBoardProposalResult,
} from "./proposal";
export {
  appendSmartInkStrokeSession,
  buildSmartInkRelationGraph,
  createSmartInkHardNegativeFixtures,
  createSmartInkTrace,
  extractSmartInkV2Features,
  recognizeSmartInkV2,
  recordSmartInkV2ShadowDiagnostic,
  smartInkSessionPolicy,
  smartInkV2DefaultPolicy,
  smartInkV2GoldQualityTargets,
  smartInkV2Version,
  subscribeSmartInkV2ShadowDiagnostics,
  traceDurationMs,
  transformSmartInkMetamorphic,
  SmartInkFieldCorpusRecorder,
  smartInkFieldCorpusSchemaVersion,
  smartInkV2FeatureNames,
  trainSmartInkLinearModel,
  type SmartInkFieldCorpus,
  type SmartInkFieldCorpusSample,
  type SmartInkLinearModelArtifact,
  type SmartInkTrainingExample,
  type SmartInkRelation,
  type SmartInkRelationKind,
  type SmartInkStrokeSession,
  type SmartInkStrokeSessionItem,
  type SmartInkTrace,
  type SmartInkTracePoint,
  type SmartInkV2Candidate,
  type SmartInkV2Decision,
  type SmartInkV2DecisionStatus,
  type SmartInkV2Features,
  type SmartInkV2Kind,
  type SmartInkV2Policy,
  type SmartInkV2Score,
  type SmartInkV2ShadowDiagnostic,
  type SmartInkV2ShapeKind,
} from "./v2/public";
