export {
  addCoordinatePlotParameter,
  addCoordinatePlotSeries,
  createDefaultCoordinatePlotObject,
  createExplicitPlotSeries,
  createParametricPlotSeries,
  createRelationPlotSeries,
  coordinatePlotSeriesInput,
  fitCoordinatePlotDefinition,
  removeCoordinatePlotParameter,
  removeCoordinatePlotSeries,
  replaceCoordinatePlotSeriesKind,
  resetCoordinatePlotViewport,
  standardCoordinatePlotViewport,
  updateCoordinatePlotParameter,
  updateCoordinatePlotSeries,
  validateCoordinatePlotEditorDefinition,
  type CoordinatePlotEditorIssue,
  type CoordinatePlotIdFactory,
} from "./model";
export { updateCoordinatePlotSeriesInput } from "./series-input";
