export {
  actorId,
  boardObjectId,
  commandId,
  documentId,
  geometryImportId,
  groupId,
  plotParameterId,
  plotSeriesId,
  solid3DId,
  solidLearningAttemptId,
  solidPointId,
  solidSectionId,
  type ActorId,
  type BoardObjectId,
  type CommandId,
  type DocumentId,
  type GeometryImportId,
  type GroupId,
  type PlotParameterId,
  type PlotSeriesId,
  type Solid3DId,
  type SolidLearningAttemptId,
  type SolidPointId,
  type SolidSectionId,
} from "./board/identifiers";
export * from "./solid-3d/public";
export * from "./solid-3d-learning/public";
export {
  boardDocumentSchemaVersion,
  createEmptyBoardDocument,
  type BoardDocument,
  type CreateBoardDocumentInput,
} from "./board/document";
export type { BoardGroup } from "./board/groups";
export {
  coordinatePlotExpressionLanguage,
  maximumCoordinatePlotExpressionBudget,
  maximumCoordinatePlotParameters,
  maximumCoordinatePlotSeries,
  maximumPlotExpressionLength,
  plotLegendPositions,
  plotParameterNamePattern,
  validatePlotParameterName,
  plotLineStyles,
  plotSeriesKinds,
  validateCoordinatePlotDefinition,
  type CoordinatePlotAxes,
  type CoordinatePlotDefinition,
  type CoordinatePlotDefinitionIssue,
  type CoordinatePlotGrid,
  type CoordinatePlotLegend,
  type CoordinatePlotViewport,
  type ExplicitPlotSeries,
  type ParametricPlotSeries,
  type RelationPlotSeries,
  type PlotLegendPosition,
  type PlotLineStyle,
  type PlotParameter,
  type PlotParameterNameIssueCode,
  type PlotSeries,
  type PlotSeriesKind,
  type PlotSeriesStyle,
} from "./board/coordinate-plot";
export {
  compilePlotExpression,
  evaluatePlotExpression,
  expressionDiagnosticCodes,
  maximumEvaluationOperations,
  maximumExpressionAstDepth,
  maximumExpressionAstNodes,
  maximumExpressionLength,
  maximumExpressionTokens,
  maximumFunctionArguments,
  normalizePlotExpression,
  parsePlotRelation,
  plotExpressionContexts,
  plotRelationIsInequality,
  plotRelationOperators,
  type CompiledPlotExpression,
  type CompilePlotExpressionOptions,
  type CompilePlotExpressionResult,
  type ExpressionDiagnostic,
  type ExpressionDiagnosticCode,
  type PlotEvaluationResult,
  type PlotEvaluationUndefinedReason,
  type PlotExpressionContext,
  type ParsePlotRelationResult,
  type PlotRelationOperator,
} from "./plot-expression/public";
export {
  clipPlotEdgeToPixelRect,
  coordinatePlotSamplerVersion,
  createPlotSamplingCache,
  createPlotSamplingCacheKey,
  defaultAdaptiveTolerancePixels,
  defaultInitialIntervalPixels,
  defaultMaximumSegmentPixels,
  defaultMinimumInitialIntervals,
  maximumAdaptiveSamplingDepth,
  maximumInitialSamplingIntervals,
  maximumSamplePointsPerCoordinatePlot,
  maximumSamplePointsPerSeries,
  maximumSamplingEvaluationsPerCoordinatePlot,
  maximumSamplingCacheEntries,
  maximumSamplingEvaluationsPerSeries,
  plotDataToLocalPoint,
  plotLocalPointIsFinite,
  plotLocalToDataPoint,
  plotPixelSizeIsValid,
  plotSamplingDiagnosticCodes,
  plotViewportIsValid,
  sampleCoordinatePlotDefinition,
  sampleExplicitSeries,
  sampleParametricSeries,
  sampleRelationSeries,
  type ClippedPlotEdge,
  type CoordinatePlotSamplingInput,
  type CoordinatePlotSamplingOptions,
  type CoordinatePlotSamplingResult,
  type CoordinatePlotSeriesSamplingResult,
  type CoordinatePlotSeriesSamplingStatus,
  type ExplicitPlotSamplingInput,
  type ParametricPlotSamplingInput,
  type RelationPlotSamplingInput,
  type PlotCoordinateViewport,
  type PlotDataBounds,
  type PlotSamplingAbortSignal,
  type PlotSamplingCache,
  type PlotSamplingDiagnostic,
  type PlotSamplingDiagnosticCode,
  type PlotSamplingMetrics,
  type PlotSamplingOptions,
  type PlotSamplingStopReason,
  type SampledPlotSeries,
} from "./plot-sampling/public";
export type {
  GeometryImportRecord,
  VisualOverride,
  VisualStyleOverride,
} from "./board/geometry-imports";
export {
  createCubicBezierCenterline,
  createLegacyVectorInkSamples,
  createLinearCubicBezierCenterline,
  createLinearVectorInkDataFromPoints,
  createVectorInkData,
  createVectorInkDataFromPoints,
  defaultVectorInkPressure,
  legacyVectorInkSampleIntervalMs,
  maximumVectorInkSamples,
  normalizeVectorInkSamples,
  resolveVectorInkData,
  vectorInkCenterlinePathData,
  vectorInkDataMatchesPoints,
  vectorInkOutlinePathData,
  vectorInkSchemaVersion,
  vectorInkStrokeIsClosed,
  type CubicBezierSegment,
  type VectorInkData,
  type VectorInkSample,
  type VectorInkStrokeLike,
} from "./board/vector-ink";
export {
  boardObjectKinds,
  embeddedImageMimeTypes,
  strokeStyles,
  svgSanitizerPolicyVersion,
  type BoardObject,
  type BoardObjectKind,
  type BoardObjectSource,
  type CoordinatePlotObject,
  type EllipseObject,
  type EmbeddedImageMimeType,
  type EmbeddedImageObject,
  type LineObject,
  type ObjectStyle,
  type PenStrokeObject,
  type RectangleObject,
  type SvgObject,
  type StrokeStyle,
  type SvgViewBox,
  type TextObject,
  type UserObjectSource,
} from "./board/objects";
export {
  migrateBoardDocument01To10,
  migrateBoardDocument01To11,
  migrateBoardDocument02To10,
  migrateBoardDocument02To11,
  migrateBoardDocument10To11,
  migrateBoardDocument01To12,
  migrateBoardDocument02To12,
  migrateBoardDocument10To12,
  migrateBoardDocument11To12,
  migrateBoardDocument12To13,
  migrateBoardDocument11To13,
  migrateBoardDocument13To14,
  type BoardDocumentMigrationResult,
} from "./board/migrations";
export {
  defaultViewport,
  identityTransform,
  type Size2,
  type Transform2D,
  type Vec2,
  type ViewportState,
} from "./board/primitives";
export {
  panViewport,
  screenToWorld,
  worldToScreen,
  zoomViewportAt,
  type ZoomBounds,
} from "./board/coordinates";
export {
  boardCommandKinds,
  type AddGroupCommand,
  type AddObjectsCommand,
  type BoardCommand,
  type CommandMetadata,
  type CutContentCommand,
  type DeleteObjectsCommand,
  type ImportGeometryCommand,
  type OffsetGeometryLabelCommand,
  type MoveGroupCommand,
  type SetGroupTransformCommand,
  type MoveObjectsCommand,
  type MoveSelectionCommand,
  type PasteContentCommand,
  type RemoveGroupsCommand,
  type ReplaceObjectsCommand,
  type RenameDocumentCommand,
  type ReorderLayersCommand,
  type LayerReorderMode,
  type SetGeometryVisualStyleCommand,
  type SetSelectionLockCommand,
  type SetSelectionStyleCommand,
  type SetLayerVisibilityCommand,
  type SetViewportCommand,
  type TranslateGeometryImportCommand,
  type UpdateCoordinatePlotCommand,
  type UpdateTextCommand,
  type CreateSolid3DCommand,
  type UpdateSolid3DCommand,
  type ProjectSolid3DSectionCommand,
  type StartSolid3DLearningCommand,
  type ActSolid3DLearningCommand,
  type ResetSolid3DLearningCommand,
  type CompleteSolid3DLearningCommand,
  type RemoveSolid3DLearningCommand,
} from "./board/commands/commands";
export {
  reduceBoardDocument,
  type CommandError,
  type CommandErrorCode,
  type CommandResult,
} from "./board/commands/reducer";
export {
  batchBoardRenderItems,
  createBoardSceneSelector,
  selectBoardScene,
  selectGroupObjects,
  selectOrderedObjects,
  selectVisibleBoardItems,
  type BoardSceneSelector,
  type BoardViewportSize,
  type BoardRenderItem,
  type BoardSceneReadModel,
} from "./board/selectors";
export {
  deserializeBoardDocument,
  serializeBoardDocument,
  type BoardDocumentDeserializationResult,
  type BoardDocumentSerializationResult,
} from "./board/serialization/serialization";
export {
  readBoardDocument,
  type BoardDocumentReadResult,
} from "./board/validation/read";
export {
  validateBoardDocument,
  type BoardDocumentValidation,
  type ValidationIssue,
} from "./board/validation/validate";
export {
  localDiagnosticSchemaVersion,
  localRevisionId,
  persistenceOperationId,
  type BoardDocumentDiagnosticBundle,
  type BoardDocumentLoadResult,
  type BoardDocumentRecoveryReason,
  type BoardDocumentRecoveryRecord,
  type BoardDocumentRepository,
  type LocalRevisionId,
  type PersistenceOperationId,
  type SaveBoardDocumentInput,
  type SaveBoardDocumentResult,
} from "./ports/board-document-repository";
export type {
  BoardAccessRole,
  BoardClientEvent,
  BoardCollaborationTicket,
  BoardCommandEnvelope,
  BoardCommandOrder,
  BoardCommandPage,
  BoardEvidenceDescriptor,
  BoardPlatformRepository,
  BoardRevisionDescriptor,
  BoardServerRecovery,
  BoardSessionContext,
  BoardSyncRepository,
  BoardTranscriptLink,
  ConfirmedBoardHead,
  CurrentOrderedBoardCommandEnvelope,
  LegacyBoardCommandEnvelope,
  OrderedBoardCommand,
  OrderedBoardCommandEnvelope,
  PendingBoardCommand,
  PendingBoardCommandOrderingInput,
  PendingBoardCommandQueue,
  PushBoardCommandsResult,
  ServerBoardCommandBatch,
  ServerBoardDescriptor,
} from "./ports/board-sync-repository";

export type { JsonPrimitive, JsonValue } from "./board/json";

export {
  geometryOsRequestId,
  type GeometryOsAmbiguity,
  type GeometryOsClient,
  type GeometryOsGenerateInput,
  type GeometryOsGenerateResult,
  type GeometryOsGenerateTask,
  type GeometryOsIncompatibleContractCode,
  type GeometryOsLayoutDiagnostic,
  type GeometryOsLayoutDocument,
  type GeometryOsLayoutInput,
  type GeometryOsLayoutLabel,
  type GeometryOsLayoutPoint,
  type GeometryOsLayoutResult,
  type GeometryOsLayoutSegment,
  type GeometryOsLayoutSource,
  type GeometryOsLayoutTask,
  type GeometryOsNotice,
  type GeometryOsProblemError,
  type GeometryOsReadinessCheck,
  type GeometryOsReadinessResult,
  type GeometryOsReadinessTask,
  type GeometryOsRequestId,
  type GeometryOsValidationIssue,
  type GeometryOsValidationReport,
} from "./ports/geometryos-client";
