export {
  actorId,
  boardObjectId,
  commandId,
  documentId,
  geometryImportId,
  groupId,
  type ActorId,
  type BoardObjectId,
  type CommandId,
  type DocumentId,
  type GeometryImportId,
  type GroupId,
} from "./board/identifiers";
export {
  boardDocumentSchemaVersion,
  createEmptyBoardDocument,
  type BoardDocument,
  type CreateBoardDocumentInput,
} from "./board/document";
export type { BoardGroup } from "./board/groups";
export type {
  GeometryImportRecord,
  VisualOverride,
  VisualStyleOverride,
} from "./board/geometry-imports";
export {
  boardObjectKinds,
  strokeStyles,
  svgSanitizerPolicyVersion,
  type BoardObject,
  type BoardObjectKind,
  type BoardObjectSource,
  type EllipseObject,
  type ImageObject,
  type LineObject,
  type ObjectStyle,
  type PenStrokeObject,
  type RectangleObject,
  type SvgObject,
  type StrokeStyle,
  type SvgViewBox,
  type TextObject,
  type UserObjectSource,
} from "./board/objects";
export {
  migrateBoardDocument01To10,
  migrateBoardDocument02To10,
  type BoardDocumentMigrationResult,
} from "./board/migrations";
export {
  defaultViewport,
  identityTransform,
  type Size2,
  type Transform2D,
  type Vec2,
  type ViewportState,
} from "./board/primitives";
export {
  panViewport,
  screenToWorld,
  worldToScreen,
  zoomViewportAt,
  type ZoomBounds,
} from "./board/coordinates";
export {
  boardCommandKinds,
  type AddGroupCommand,
  type AddObjectsCommand,
  type BoardCommand,
  type CommandMetadata,
  type CutContentCommand,
  type DeleteObjectsCommand,
  type ImportGeometryCommand,
  type OffsetGeometryLabelCommand,
  type MoveGroupCommand,
  type MoveObjectsCommand,
  type MoveSelectionCommand,
  type PasteContentCommand,
  type RemoveGroupsCommand,
  type ReplaceObjectsCommand,
  type RenameDocumentCommand,
  type ReorderLayersCommand,
  type LayerReorderMode,
  type SetGeometryVisualStyleCommand,
  type SetSelectionLockCommand,
  type SetSelectionStyleCommand,
  type SetLayerVisibilityCommand,
  type SetViewportCommand,
  type TranslateGeometryImportCommand,
  type UpdateTextCommand,
} from "./board/commands/commands";
export {
  reduceBoardDocument,
  type CommandError,
  type CommandErrorCode,
  type CommandResult,
} from "./board/commands/reducer";
export {
  batchBoardRenderItems,
  createBoardSceneSelector,
  selectBoardScene,
  selectGroupObjects,
  selectOrderedObjects,
  selectVisibleBoardItems,
  type BoardSceneSelector,
  type BoardViewportSize,
  type BoardRenderItem,
  type BoardSceneReadModel,
} from "./board/selectors";
export {
  deserializeBoardDocument,
  serializeBoardDocument,
  type BoardDocumentDeserializationResult,
  type BoardDocumentSerializationResult,
} from "./board/serialization/serialization";
export {
  readBoardDocument,
  type BoardDocumentReadResult,
} from "./board/validation/read";
export {
  validateBoardDocument,
  type BoardDocumentValidation,
  type ValidationIssue,
} from "./board/validation/validate";
export {
  localDiagnosticSchemaVersion,
  localRevisionId,
  persistenceOperationId,
  type BoardDocumentDiagnosticBundle,
  type BoardDocumentLoadResult,
  type BoardDocumentRecoveryReason,
  type BoardDocumentRecoveryRecord,
  type BoardDocumentRepository,
  type LocalRevisionId,
  type PersistenceOperationId,
  type SaveBoardDocumentInput,
  type SaveBoardDocumentResult,
} from "./ports/board-document-repository";
export type {
  BoardAccessRole,
  BoardCommandEnvelope,
  BoardCommandPage,
  BoardCollaborationTicket,
  BoardClientEvent,
  BoardEvidenceDescriptor,
  BoardPlatformRepository,
  BoardRevisionDescriptor,
  BoardServerRecovery,
  BoardSessionContext,
  BoardSyncRepository,
  BoardTranscriptLink,
  ConfirmedBoardHead,
  PendingBoardCommand,
  PendingBoardCommandQueue,
  PushBoardCommandsResult,
  ServerBoardCommandBatch,
  ServerBoardDescriptor,
} from "./ports/board-sync-repository";

export type { JsonPrimitive, JsonValue } from "./board/json";

export {
  geometryOsRequestId,
  type GeometryOsAmbiguity,
  type GeometryOsClient,
  type GeometryOsGenerateInput,
  type GeometryOsGenerateResult,
  type GeometryOsGenerateTask,
  type GeometryOsIncompatibleContractCode,
  type GeometryOsLayoutDiagnostic,
  type GeometryOsLayoutDocument,
  type GeometryOsLayoutInput,
  type GeometryOsLayoutLabel,
  type GeometryOsLayoutPoint,
  type GeometryOsLayoutResult,
  type GeometryOsLayoutSegment,
  type GeometryOsLayoutSource,
  type GeometryOsLayoutTask,
  type GeometryOsNotice,
  type GeometryOsProblemError,
  type GeometryOsReadinessCheck,
  type GeometryOsReadinessResult,
  type GeometryOsReadinessTask,
  type GeometryOsRequestId,
  type GeometryOsValidationIssue,
  type GeometryOsValidationReport,
} from "./ports/geometryos-client";
